version: "3"

services:
  author-service:
    image: author-service
    build: ./author-service
    ports:
      - "9998:9998"
    networks:
      - app-network
    depends_on:
      - eureka-server
      - gateway
      - authentication-service

  book-service:
    image: book-service
    build: ./book-service
    ports:
      - "9999:9999"
    networks:
      - app-network
    depends_on:
      - eureka-server
      - gateway
      - authentication-service

  gateway:
    image: gateway
    build: ./apigateway
    ports:
      - "9996:9996"
    networks:
      - app-network
    depends_on:
      - eureka-server

  eureka-server:
    image: eureka-server
    build: ./eureka-server
    ports:
      - "8762:8762"
    networks:
      - app-network

  authentication-service:
    image: auth-service
    build: ./authentication_service
    ports:
      - "9997:9997"
    networks:
      - app-network
    depends_on:
      - eureka-server
      - gateway

  mysql-author:
    image: mysql:latest
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: pass@word1
      MYSQL_DATABASE: author_db
    ports:
      - "3307:3306"

  mysql-book:
    image: mysql:latest
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: pass@word1
      MYSQL_DATABASE: book_db
    ports:
      - "3308:3306"

  mysql-users:
    image: mysql:latest
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: pass@word1
      MYSQL_DATABASE: users_db
    ports:
      - "3309:3306"

networks:
  app-network:

