eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

spring:
  application:
    name: book_service
  datasource:
    url: jdbc:mysql://localhost:3306/book_db
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
        show-sql: true

server:
  port: 9999

