spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_db
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: authentication_service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9997
